config/routes.rb
Rails.application.routes.draw do
  resources :provenance_records do
    get :confirm_destroy
  end
  get 'clear_settings', to: 'provenance_records#clear_settings', via: [:destroy], as: :clear_settings
  get 'delete_file_attachment/:id', to: 'provenance_records#delete_file_attachment', via: [:destroy], as: :delete_file_attachment
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/provenance_record.rb
class ProvenanceRecord < ApplicationRecord
    has_many_attached :provenance_files
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/provenance_records_controller.rb
class ProvenanceRecordsController < ApplicationController
  http_basic_authenticate_with name: "username", password: "changeme"
  before_action :set_provenance_record, only: %i[ show edit update destroy ]
  before_action :persist_params

  # GET /provenance_records or /provenance_records.json
  def index
    session[:show_unlisted] = params[:show_unlisted] if params[:show_unlisted].present?
    session[:column] = params[:column] if params[:column].present?
    session[:direction] = params[:direction] if params[:direction].present?
    session[:q] = params[:q] if params[:q].present?

    session[:column] = "accession_number" if !session[:column].present?
    session[:direction] = "asc" if !session[:direction].present?
    
    @provenance_records = ProvenanceRecord.all
    @provenance_records = ProvenanceRecord.where('collection_name like ? ', "%#{session[:q]}%") if session[:q].present?
    
    if (!session[:show_unlisted] || session[:show_unlisted] == "false")
      @provenance_records = @provenance_records.where(unlist: false)
    end

    if (session[:column])
      @provenance_records = @provenance_records.order("#{session[:column]} #{session[:direction]}")
    end

    if (session[:column] == "accession_number")
      @provenance_records = @provenance_records.sort_by{|p| p.accession_number.to_i}
      if session[:direction] == "desc"
        @provenance_records = @provenance_records.reverse
      end
    end
  end

  # GET /provenance_records/1 or /provenance_records/1.json
  def show
  end

  # GET /provenance_records/new
  def new
    @provenance_record = ProvenanceRecord.new
  end

  # GET /provenance_records/1/edit
  def edit
  end

  # Based on: https://gorails.com/forum/how-do-i-create-a-delete-button-for-images-uploaded-with-active-storage
  def delete_file_attachment
    @file = ActiveStorage::Attachment.find(params[:id])
    @file.purge
    redirect_back(fallback_location: request.referer)
  end

  def clear_settings
    session[:show_unlisted] = nil
    session[:column] = nil
    session[:direction] = nil
    session[:q] = nil

    redirect_to :provenance_records
  end

  # POST /provenance_records or /provenance_records.json
  def create
    @provenance_record = ProvenanceRecord.new(provenance_record_params)

    respond_to do |format|
      if @provenance_record.save
        format.html { redirect_to provenance_record_url(@provenance_record), notice: "Provenance record was successfully created." }
        format.json { render :show, status: :created, location: @provenance_record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @provenance_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provenance_records/1 or /provenance_records/1.json
  def update
    respond_to do |format|
      if @provenance_record.update(provenance_record_params)
        format.html { redirect_to provenance_record_url(@provenance_record), notice: "Provenance record was successfully updated." }
        format.json { render :show, status: :ok, location: @provenance_record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @provenance_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provenance_records/1 or /provenance_records/1.json
  def destroy
    @provenance_record.destroy

    respond_to do |format|
      format.html { redirect_to provenance_records_url, notice: "Provenance record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def confirm_destroy
    @provenance_record = ProvenanceRecord.find(params[:provenance_record_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provenance_record
      @provenance_record = ProvenanceRecord.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def provenance_record_params
      params.require(:provenance_record).permit(:accession_number, :collection_name, :collection_name_alpha, :start_year, :end_year, :date_expression, :year_received, :month_received, :day_received, :linear_feet, :containers, :finding_aid_link, :unlist, :provenance_files => [])
    end

    def persist_params
      session[:column] ||= params[:column]
      session[:direction] ||= params[:direction]
      session[:show_unlisted] ||= params[:show_unlisted]
      session[:q] ||= params[:q]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/provenance_records_helper.rb
module ProvenanceRecordsHelper
    def sort_link(column:, label:, class: nil)
        if column == params[:column]
            link_to(label, provenance_records_path(column: column, direction: next_direction), class: "link-light")
        else
            link_to(label, provenance_records_path(column: column, direction: 'asc'), class: "link-light")
        end
    end

    def toggle_unlisted_link(show_unlisted:, label:)
        if (show_unlisted == "true")
            show_unlisted = "false"
        else
            show_unlisted = "true"
        end
        link_to(label, provenance_records_path(show_unlisted: show_unlisted))
    end

    def next_direction
        params[:direction] == 'asc' ? 'desc' : 'asc'
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Provenance</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/provenance_records/_form.html.erb
<%= form_with(model: provenance_record) do |form| %>
  <% if provenance_record.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(provenance_record.errors.count, "error") %> prohibited this provenance_record from being saved:</h2>

      <ul>
        <% provenance_record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row mt-3">
    <div class="col-md-12">
      <%= form.label :unlist, class: "form-label" %>
      <%= form.check_box :unlist, class: "form-check-input" %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-md-2">
      <%= form.label :accession_number, class: "form-label" %>
      <%= form.text_field :accession_number, class: "form-control" %>
    </div>

    <div class="col-md-5">
      <%= form.label :collection_name, class: "form-label" %>
      <%= form.text_field :collection_name, class: "form-control" %>
    </div>
    <div class="col-md-5">
      <%= form.label :collection_name_alpha, class: "form-label" %>
      <%= form.text_field :collection_name_alpha, class: "form-control" %>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-3">
      <%= form.label :start_year, class: "form-label" %>
      <%= form.number_field :start_year, class: "form-control" %>
    </div>

    <div class="col-md-3">
      <%= form.label :end_year, class: "form-label" %>
      <%= form.number_field :end_year, class: "form-control" %>
    </div>

    <div class="col-md-6">
      <%= form.label :date_expression, class: "form-label" %>
      <%= form.text_field :date_expression, class: "form-control" %>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-4">
      <%= form.label :year_received, class: "form-label" %>
      <%= form.number_field :year_received, class: "form-control" %>
    </div>

    <div class="col-md-4">
      <%= form.label :month_received, class: "form-label" %>
      <%= form.number_field :month_received, class: "form-control" %>
    </div>

    <div class="col-md-4">
      <%= form.label :day_received, class: "form-label" %>
      <%= form.number_field :day_received, class: "form-control" %>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-3">
      <%= form.label :linear_feet, class: "form-label" %>
      <%= form.text_field :linear_feet, class: "form-control" %>
    </div>

    <div class="col-md-4">
      <%= form.label :containers, class: "form-label" %>
      <%= form.text_field :containers, class: "form-control" %>
    </div>

    <div class="col-md-5">
      <%= form.label  :finding_aid_link, class: "form-label" %>
      <%= form.text_field :finding_aid_link, class: "form-control" %>
    </div>
  </div>

  <div class="col-md-12">
    <%= form.label :provenance_files, class: "form-label" %>
    
    <% # Keep previously uploaded files using the strategy described here: https://stackoverflow.com/a/58351326 %>
    <%= form.file_field :provenance_files, multiple: true, direct_upload: true, class: "form-control" %>
    <% form.object.provenance_files.each do |file| %>
      <%= form.hidden_field :provenance_files, value: file.signed_id, multiple: true %>
      <% if file.representable? %>
        <%= image_tag file.representation(resize_to_limit: [200, 200]) %>
      <% else %>
        <%= link_to file.filename, rails_blob_path(file, disposition: 'attachment') %>
      <% end%>
      <%= link_to 'Delete file', delete_file_attachment_url(file), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    <% end %>
  </div>

  <div class="row mt-4">
    <div class="col-12">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/provenance_records/_provenance_record.html.erb
<div id="<%= dom_id provenance_record %>" class="mt-3">
  <% if provenance_record.unlist %>
    <p>
      <strong class="fs-2 text-danger">UNLISTED</strong>
    </p>
  <% end %>

  <div class="mb-4">
    <div class="fs-3"><%= provenance_record.collection_name %>, <%= provenance_record.date_expression %></div>
    <div class="fs-5">HI Archives collection no. <%= provenance_record.accession_number %></div>
    <% if !provenance_record.linear_feet.blank? %>
      <div class="fs-5"><%= pluralize(provenance_record.linear_feet, 'linear foot', 'linear feet') %> (<%= provenance_record.containers %>)</div>
    <% end %>
  </div>

  <% if provenance_record.finding_aid_link %>
    <div>
      <strong>Finding aid:</strong>
      <a href="<%= provenance_record.finding_aid_link %>"><%= provenance_record.finding_aid_link %></a>
    </div>
  <% end %>

  <div>
    <strong>Alphabetical name:</strong>
    <%= provenance_record.collection_name_alpha %>
  </div>

  <div>
    <strong>Main date range:</strong>
    <%= provenance_record.start_year %>–<%=provenance_record.end_year %>
  </div>

  <div>
    <strong>Detailed date range:</strong>
    <%= provenance_record.date_expression %>
  </div>

  <div>
    <strong>Received:</strong>
    <%= provenance_record.year_received.presence || "????" %>–<%= provenance_record.month_received.presence || "??" %>–<%= provenance_record.day_received.presence || "??" %>
  </div>

  <% if !provenance_record.provenance_files.blank? %>
    <div class="mt-3">
      <strong>Files:</strong>
      <div class="row">
        <% provenance_record.provenance_files.each do |file| %>
          <div class="col-md-4 col-lg-3 mb-3">
            <% if file.representable? %>
              <%= link_to(image_tag(file.representation(resize_to_limit: [200, 200])), file) %>
            <% else %>
              <%= link_to file.filename, rails_blob_path(file, disposition: 'attachment') %>
            <% end%>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/provenance_records/_table.html.erb
<%= turbo_frame_tag "table" do %>
  <div class="d-flex justify-content-end">
    <%= form_with url: provenance_records_path, method: "get" do |form| %>
      <%= form.label :q, "Search collection names:", class: "form-label" %>
      <%= form.text_field :q, value: session[:q], class: "form-control" %>
    <% end %>
    <%= link_to "Clear settings", :clear_settings %>
  </div>
  <% unlisted_toggle_text = session[:show_unlisted] == "true" ? "Hide unlisted records" : "Show unlisted records" %>
  <%= toggle_unlisted_link(show_unlisted: session[:show_unlisted], label: unlisted_toggle_text) %>
  <table class="table table-striped">
    <thead class="table-dark">
      <tr>
        <% if session[:show_unlisted] == "true" %>
          <th scope="col">Unlisted</th>
        <% end %>
        <th scope="col"><%= sort_link(column: "accession_number", label: "Accession#") %></th>
        <th scope="col"><%= sort_link(column: "collection_name_alpha", label: "Collection name (alpha)") %></th>
        <th scope="col"><%= sort_link(column: "start_year", label: "Date range") %></th>
        <th scope="col"><%= sort_link(column: "linear_feet", label: "Linear feet") %></th>
        <th scope="col">Finding aid</th>
      </tr>
    </thead>
    <tbody>
    <% provenance_records.each do |provenance_record| %>
      <tr>
        <% if session[:show_unlisted] == "true" %>
          <td><%= provenance_record.unlist ? "X" : "" %></th>
        <% end %>
        <td>
          <%= provenance_record.accession_number %>
        </td>
        <td>
          <%= link_to(provenance_record.collection_name_alpha, provenance_record) %>
          <% if provenance_record.collection_name_alpha.blank? %>
            <%= link_to(provenance_record.collection_name.presence || provenance_record.accession_number.presence || '[no title]', provenance_record) %>
          <% end %>
        </td>
        <td>
          <%= provenance_record.date_expression %>
        </td>
        <td>
          <%= provenance_record.linear_feet %>
        </td>
        <td>
          <% if !provenance_record.finding_aid_link.blank? %>
            <%= link_to "link", provenance_record.finding_aid_link %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/provenance_records/confirm_destroy.html.erb
<p style="color: green"><%= notice %></p>

<div class="fs-2 fw-bold">Are you <em>absolutely sure</em> you want to delete <%= @provenance_record.accession_number %>: <%= @provenance_record.collection_name %>?</div>
<div class="text-center mt-5">
    <%= button_to "Destroy this provenance record", @provenance_record, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: "btn btn-danger btn-lg fw-bold" %>
    <br>
    <%= button_to "Cancel", 'javascript:history.back()', method: 'get', class: "btn btn-secondary btn-lg" %>
</div>

app/views/provenance_records/edit.html.erb
<h1>Editing provenance record</h1>

<%= render "form", provenance_record: @provenance_record %>

<br>

<div>
  <%= link_to "Show this provenance record", @provenance_record %> |
  <%= link_to "Back to provenance records", provenance_records_path %>
</div>

app/views/provenance_records/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Provenance records</h1>

<div class="text-end"><a href="<%= request.protocol %>logout:logout@<%= request.port != 80 ? request.host_with_port : request.host %><%= request.env['PATH_INFO'] %>">Log out</a></div>

<%= render "table", provenance_records: @provenance_records %>

<%= link_to "New provenance record", new_provenance_record_path %>

app/views/provenance_records/new.html.erb
<h1>New provenance record</h1>

<%= render "form", provenance_record: @provenance_record %>

<br>

<div>
  <%= link_to "Back to provenance records", provenance_records_path %>
</div>

app/views/provenance_records/show.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "Back to list", provenance_records_path, class: "fs-3" %>

<%= render @provenance_record %>

<div class="mt-3">
  <%= link_to "Edit this provenance record", edit_provenance_record_path(@provenance_record) %>
  <br>
  <%= link_to "Destroy this provenance record", provenance_record_confirm_destroy_path(@provenance_record), class: "text-danger fw-bold" %>
</div>